//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public string ItemCode { get; set; }
        public short Quantity { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int PersonId { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
